### ISSUE TITLE
User Accounts---Epic

### ISSUE THREAD

**Issue by reltoom** [reltoom/Meal-Share#3]
This Epic tracks the progress of implementing *user accounts*.

## Tasks
- [x] User can create an account
- [x] User can sign into account
- [x] User can log out of account
- [x] User can edit username
- [x] User can change password
