### ISSUE TITLE
Profile Epic

### ISSUE THREAD

**Issue by reltoom** [reltoom/Meal-Share#30]
This Epic tracks the progress of implementing *the Profile page*.

## Tasks
- [x] There is a page for the logged in user
- [x] shows users posts
- [x] shows number of liked posts by the user
- [x] shows number of followed users by the user
- [x] shows number of users following the user.
- [x] Can edit profile image and bio
