### ISSUE TITLE
Epic Posts

### ISSUE THREAD

**Issue by reltoom** [reltoom/Meal-Share#9]
This Epic tracks the progress of implementing *Posts*.

## Tasks
- [x] Create a Post
- [x] View a list of Posts
- [x] View a singe Post
- [x] Edit a Post
- [x] Delete a Post
- [x] Like/unlike a Post
- [x] Comment on a Post
- [x] View Comments
- [x] Edit my comment
- [x] Delete my comment
- [x] User can search for posts
